
export const GlobalMetricsUrl = 'https://pro-api.coinmarketcap.com/v1/global-metrics/quotes/latest'
export const KucoinsMarketsUrl = 'https://api.kucoin.com/api/v1/symbols'
export const BittrexesMarketsUrl = 'https://api.bittrex.com/v3/markets'
export const CoinexesMarketsUrl = 'https://api.coinex.com/v1/market/info'
export const BinanceMarketsUrl = 'https://api.binance.com/api/v3/exchangeInfo'
export const CryptosUrl = 'https://api.coingecko.com/api/v3/search'
export const wsConnectionInfoUrl = 'https://openapi-v2.kucoin.com/api/v1/bullet-public'
export const kucoinMarketPriceUrl = 'https://openapi-v2.kucoin.com/api/v1/market/candles?type=1day&symbol=:symbol'
export const bittrexMarketPriceUrl = 'https://api.bittrex.com/v3//markets/:symbol/candles/DAY_1/recent'
export const binanceMarketPriceUrl = 'https://api.binance.com/api/v3/klines?symbol=:symbol&interval=1d'
export const coinexMarketPriceUrl = 'https://api.coinex.com/v1/market/kline'
